<a href="https://colab.research.google.com/github/bimald986-cell/90-Days-of-AI/blob/main/Day_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

candidates = {
    "Name": ["Asha", "Ravi", "Maya", "Omar", "Sara", "Daniel"],
    "Subject": ["Math", "English", "Science", "Math", "English", "Science"],
    "Experience": [5, 2, 7, 3, 6, 4],
    "ExpectedSalary": [1200, 900, 1500, 1100, 1300, 1250]
}

df = pd.DataFrame(candidates)

df

     Name  Subject  Experience  ExpectedSalary
0    Asha     Math           5            1200
1    Ravi  English           2             900
2    Maya  Science           7            1500
3    Omar     Math           3            1100
4    Sara  English           6            1300
5  Daniel  Science           4            1250

In [ ]:
df[df["Experience"] >= 5]

   Name  Subject  Experience  ExpectedSalary
0  Asha     Math           5            1200
2  Maya  Science           7            1500
4  Sara  English           6            1300

In [ ]:
df["SeniorCandidate"] = df["Experience"] >= 5

df

     Name  Subject  Experience  ExpectedSalary  SeniorCandidate
0    Asha     Math           5            1200             True
1    Ravi  English           2             900            False
2    Maya  Science           7            1500             True
3    Omar     Math           3            1100            False
4    Sara  English           6            1300             True
5  Daniel  Science           4            1250            False

In [ ]:
df["HighSalary"] = df["ExpectedSalary"] >= 1300
df

     Name  Subject  Experience  ExpectedSalary  SeniorCandidate  HighSalary
0    Asha     Math           5            1200             True       False
1    Ravi  English           2             900            False       False
2    Maya  Science           7            1500             True        True
3    Omar     Math           3            1100            False       False
4    Sara  English           6            1300             True        True
5  Daniel  Science           4            1250            False       False

In [ ]:
df["PriorityCandidate"] = (df["Experience"] >= 5) & (df["ExpectedSalary"] <= 1300)
df

,Name,Subject,Experience,ExpectedSalary,SeniorCandidate,HighSalary,PriorityCandidate
0,Asha,Math,5,1200,True,False,True
1,Ravi,English,2,900,False,False,False
2,Maya,Science,7,1500,True,True,False
3,Omar,Math,3,1100,False,False,False
4,Sara,English,6,1300,True,True,True
5,Daniel,Science,4,1250,False,False,False

In [ ]:
df["SalaryCategory"] = np.where(
    df["ExpectedSalary"] >= 1300,
    "High",
    "Standard"
)
df

,Name,Subject,Experience,ExpectedSalary,SeniorCandidate,HighSalary,PriorityCandidate,SalaryCategory
0,Asha,Math,5,1200,True,False,True,Standard
1,Ravi,English,2,900,False,False,False,Standard
2,Maya,Science,7,1500,True,True,False,High
3,Omar,Math,3,1100,False,False,False,Standard
4,Sara,English,6,1300,True,True,True,High
5,Daniel,Science,4,1250,False,False,False,Standard

In [ ]:
conditions = [df["Experience"] >= 5, df["Experience"] >= 4]
choices = ["Senior", "Mid"]
df["ExperienceLevel"] = np.select(
    conditions,
    choices,
    default="Junior"
)
df

,Name,Subject,Experience,ExpectedSalary,SeniorCandidate,HighSalary,PriorityCandidate,SalaryCategory,ExperienceLevel
0,Asha,Math,5,1200,True,False,True,Standard,Senior
1,Ravi,English,2,900,False,False,False,Standard,Junior
2,Maya,Science,7,1500,True,True,False,High,Senior
3,Omar,Math,3,1100,False,False,False,Standard,Junior
4,Sara,English,6,1300,True,True,True,High,Senior
5,Daniel,Science,4,1250,False,False,False,Standard,Mid

In [ ]:
conditions = [
    df["Experience"] >= 5,
    df["Experience"] >= 3
]

choices = [
    "Senior",
    "Mid"
]

df["ExperienceLevel"] = np.select(
    conditions,
    choices,
    default="Junior"
)

df

,Name,Subject,Experience,ExpectedSalary,SeniorCandidate,HighSalary,PriorityCandidate,SalaryCategory,ExperienceLevel
0,Asha,Math,5,1200,True,False,True,Standard,Senior
1,Ravi,English,2,900,False,False,False,Standard,Junior
2,Maya,Science,7,1500,True,True,False,High,Senior
3,Omar,Math,3,1100,False,False,False,Standard,Mid
4,Sara,English,6,1300,True,True,True,High,Senior
5,Daniel,Science,4,1250,False,False,False,Standard,Mid

In [ ]:
df["MatchScore"] = (
    (df["Experience"] >= 5) * 2
    + (df["ExpectedSalary"] <= 1300) * 1
)

df

,Name,Subject,Experience,ExpectedSalary,SeniorCandidate,HighSalary,PriorityCandidate,SalaryCategory,ExperienceLevel,MatchScore
0,Asha,Math,5,1200,True,False,True,Standard,Senior,3
1,Ravi,English,2,900,False,False,False,Standard,Junior,1
2,Maya,Science,7,1500,True,True,False,High,Senior,2
3,Omar,Math,3,1100,False,False,False,Standard,Mid,1
4,Sara,English,6,1300,True,True,True,High,Senior,3
5,Daniel,Science,4,1250,False,False,False,Standard,Mid,1

In [ ]:
df["OPENScore"] = (
    (df["Experience"] >= 5) * 3
    + (df["ExpectedSalary"] <= 1300) * 2 + (df["Subject"] == "Science") * 1
)

df

,Name,Subject,Experience,ExpectedSalary,SeniorCandidate,HighSalary,PriorityCandidate,SalaryCategory,ExperienceLevel,MatchScore,OPENScore
0,Asha,Math,5,1200,True,False,True,Standard,Senior,3,5
1,Ravi,English,2,900,False,False,False,Standard,Junior,1,2
2,Maya,Science,7,1500,True,True,False,High,Senior,2,4
3,Omar,Math,3,1100,False,False,False,Standard,Mid,1,2
4,Sara,English,6,1300,True,True,True,High,Senior,3,5
5,Daniel,Science,4,1250,False,False,False,Standard,Mid,1,3

In [ ]:
df["MatchDecision"] = np.where(
    df["OPENScore"] >= 4,
    "Strong Match",
    "review"
)
df

,Name,Subject,Experience,ExpectedSalary,SeniorCandidate,HighSalary,PriorityCandidate,SalaryCategory,ExperienceLevel,MatchScore,OPENScore,MatchDecision
0,Asha,Math,5,1200,True,False,True,Standard,Senior,3,5,Strong Match
1,Ravi,English,2,900,False,False,False,Standard,Junior,1,2,review
2,Maya,Science,7,1500,True,True,False,High,Senior,2,4,Strong Match
3,Omar,Math,3,1100,False,False,False,Standard,Mid,1,2,review
4,Sara,English,6,1300,True,True,True,High,Senior,3,5,Strong Match
5,Daniel,Science,4,1250,False,False,False,Standard,Mid,1,3,review

In [ ]:
df["MatchDecision"] = np.where(
    df["OPENScore"] >= 4,
    "Strong Match",
    "Review"
)
df

,Name,Subject,Experience,ExpectedSalary,SeniorCandidate,HighSalary,PriorityCandidate,SalaryCategory,ExperienceLevel,MatchScore,OPENScore,MatchDecision
0,Asha,Math,5,1200,True,False,True,Standard,Senior,3,5,Strong Match
1,Ravi,English,2,900,False,False,False,Standard,Junior,1,2,Review
2,Maya,Science,7,1500,True,True,False,High,Senior,2,4,Strong Match
3,Omar,Math,3,1100,False,False,False,Standard,Mid,1,2,Review
4,Sara,English,6,1300,True,True,True,High,Senior,3,5,Strong Match
5,Daniel,Science,4,1250,False,False,False,Standard,Mid,1,3,Review

In [ ]:
df["ranked_candidates"] = filtered = df["MatchDecision"]

sorted_data = filtered.sort_values(
    "OPENScore",
    ascending=False
)

result = sorted_data[
    ["Name", "Subject", "Experience", "ExpectedSalary", "OPENScore"]
]

result
df["ranked_candidates"]

TypeError: Series.sort_values() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

In [ ]:
ranked_candidates = df.sort_values(
    "OPENScore",
    ascending=False
)

ranked_candidates

,Name,Subject,Experience,ExpectedSalary,SeniorCandidate,HighSalary,PriorityCandidate,SalaryCategory,ExperienceLevel,MatchScore,OPENScore,MatchDecision,ranked_candidates
0,Asha,Math,5,1200,True,False,True,Standard,Senior,3,5,Strong Match,Strong Match
4,Sara,English,6,1300,True,True,True,High,Senior,3,5,Strong Match,Strong Match
2,Maya,Science,7,1500,True,True,False,High,Senior,2,4,Strong Match,Strong Match
5,Daniel,Science,4,1250,False,False,False,Standard,Mid,1,3,Review,Review
1,Ravi,English,2,900,False,False,False,Standard,Junior,1,2,Review,Review
3,Omar,Math,3,1100,False,False,False,Standard,Mid,1,2,Review,Review

In [ ]:
strong_candidates = df ["ranked_candidates"]
df.sort_values(
    "OPENScore",
    ascending=False
)

strong_candidates

0    Strong Match
1          Review
2    Strong Match
3          Review
4    Strong Match
5          Review
Name: ranked_candidates, dtype: object

In [ ]:
strong_candidates = df[df["OPENScore"] >= 4].sort_values(
    "OPENScore",
    ascending=False
)

strong_candidates

,Name,Subject,Experience,ExpectedSalary,SeniorCandidate,HighSalary,PriorityCandidate,SalaryCategory,ExperienceLevel,MatchScore,OPENScore,MatchDecision,ranked_candidates
0,Asha,Math,5,1200,True,False,True,Standard,Senior,3,5,Strong Match,Strong Match
4,Sara,English,6,1300,True,True,True,High,Senior,3,5,Strong Match,Strong Match
2,Maya,Science,7,1500,True,True,False,High,Senior,2,4,Strong Match,Strong Match

In [ ]:
science_candidates = df[df["Subject"] == "Science"].sort_values(
    "Subject"
)
science_candidates

,Name,Subject,Experience,ExpectedSalary,SeniorCandidate,HighSalary,PriorityCandidate,SalaryCategory,ExperienceLevel,MatchScore,OPENScore,MatchDecision,ranked_candidates
2,Maya,Science,7,1500,True,True,False,High,Senior,2,4,Strong Match,Strong Match
5,Daniel,Science,4,1250,False,False,False,Standard,Mid,1,3,Review,Review

In [ ]:
science_candidates = df[df["Subject"] == "Science"]

science_candidates

,Name,Subject,Experience,ExpectedSalary,SeniorCandidate,HighSalary,PriorityCandidate,SalaryCategory,ExperienceLevel,MatchScore,OPENScore,MatchDecision,ranked_candidates
2,Maya,Science,7,1500,True,True,False,High,Senior,2,4,Strong Match,Strong Match
5,Daniel,Science,4,1250,False,False,False,Standard,Mid,1,3,Review,Review

In [6]:
experienced_science_candidates = df[(df["Subject"] == "Science") & (df["Experience"] >= 4)]

NameError: name 'df' is not defined

In [7]:
affordable_experienced = df[(df["Experience"] >= 4) & (df["ExpectedSalary"] <= 1300)]

NameError: name 'df' is not defined

In [8]:
import numpy as np

scores = np.array([72, 85, 91, 68, 88, 95])

scores

array([72, 85, 91, 68, 88, 95])

In [9]:
scores.mean()

np.float64(83.16666666666667)

In [10]:
scores.max()

np.int64(95)

In [11]:
scores.min()

np.int64(68)

In [12]:
scores.sum()

np.int64(499)