<a href="https://colab.research.google.com/github/bimald986-cell/90-Days-of-AI/blob/main/Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = {
    "Name": ["Maya", "Arjun", "Sara", "Omar", "Lina"],
    "Department": ["HR", "IT", "HR", "Finance", "IT"],
    "Salary": [650, 900, 720, 850, 780]
}

df = pd.DataFrame(data)

print(df)

    Name Department  Salary
0   Maya         HR     650
1  Arjun         IT     900
2   Sara         HR     720
3   Omar    Finance     850
4   Lina         IT     780

In [2]:
df[df["Salary"] > 750] &

    Name Department  Salary
1  Arjun         IT     900
3   Omar    Finance     850
4   Lina         IT     780

In [7]:
df[(df["Department"] == "IT") & (df["Salary"] > 800)]

    Name Department  Salary
1  Arjun         IT     900

In [8]:
df[(df["Department"] == "HR") | (df["Salary"] > 800)]

    Name Department  Salary
0   Maya         HR     650
1  Arjun         IT     900
2   Sara         HR     720
3   Omar    Finance     850

In [12]:
df[(df["Salary"] > 700)]
df[["Name", "Salary"]]print("Name", "Salary")

SyntaxError: invalid syntax (1151902377.py, line 2)

In [13]:
df[df["Salary"] > 700][["Name", "Salary"]]

    Name  Salary
1  Arjun     900
2   Sara     720
3   Omar     850
4   Lina     780

In [18]:
df[(df["Department"] == "HR") & (df["Salary"] >= 700)][["Name", "Salary"]]

   Name  Salary
2  Sara     720

In [19]:
df[(df["Department"] == "IT") | (df["Department"] == "Finance") & (df["Salary"] > 800)][["Name", "Department", "Salary"]]

    Name Department  Salary
1  Arjun         IT     900
3   Omar    Finance     850
4   Lina         IT     780

In [20]:
df[
    (df["Department"].isin(["IT", "Finance"]))
    & (df["Salary"] >= 800)
    ][["Name", "Department", "Salary"]]

    Name Department  Salary
1  Arjun         IT     900
3   Omar    Finance     850

In [21]:
df[(df["Department"].isin(["HR", "Finance"])) & (df["Salary"] >= 700)][["Name", "Department", "Salary"]]

   Name Department  Salary
2  Sara         HR     720
3  Omar    Finance     850

In [23]:
df.sort_values("Salary")
df[(df["Department"].isin(["HR", "IT"])) & (df["Salary"] >= 700)][["Name", "Salary"]]
df.sort_values("Salary", ascending=False)

    Name Department  Salary
1  Arjun         IT     900
3   Omar    Finance     850
4   Lina         IT     780
2   Sara         HR     720
0   Maya         HR     650

In [25]:
df.sort_values("Salary")
df[(df["Department"].isin(["HR", "IT"]))] [["Name", "Salary"]]
df.sort_values("Salary", ascending=False)

    Name Department  Salary
1  Arjun         IT     900
3   Omar    Finance     850
4   Lina         IT     780
2   Sara         HR     720
0   Maya         HR     650

In [27]:
df.sort_values("Salary")
df[(df["Department"].isin(["HR", "IT"]))]
df.sort_values("Salary", ascending=False) [["Name", "Salary"]]

    Name  Salary
1  Arjun     900
3   Omar     850
4   Lina     780
2   Sara     720
0   Maya     650

In [28]:
filtered = df[df["Department"].isin(["HR", "IT"])]

sorted_data = filtered.sort_values("Salary", ascending=False)

result = sorted_data[["Name", "Salary"]]

result

    Name  Salary
1  Arjun     900
4   Lina     780
2   Sara     720
0   Maya     650

In [29]:
df.sort_values(
    ["Department", "Salary"],
    ascending=[True, False]
)

    Name Department  Salary
3   Omar    Finance     850
2   Sara         HR     720
0   Maya         HR     650
1  Arjun         IT     900
4   Lina         IT     780

In [30]:
df.sort_values(
    ["Department", "Salary"],
    ascending=[False, True]
)

    Name Department  Salary
4   Lina         IT     780
1  Arjun         IT     900
0   Maya         HR     650
2   Sara         HR     720
3   Omar    Finance     850

In [31]:
df["Salary"].mean()

np.float64(780.0)

In [32]:
df["Salary"].min()
df["Salary"].max()
df["Salary"].sum()

np.int64(3900)

In [33]:
df[df["Department"] == "IT"] ["Salary"].mean()

np.float64(840.0)

In [34]:
df[df["Department"] == "HR"] ["Salary"].max()

720

In [35]:
df.groupby("Department")["Salary"].mean()

Department
Finance    850.0
HR         685.0
IT         840.0
Name: Salary, dtype: float64

In [36]:
df.groupby("Department")["Salary"].max()

Department
Finance    850
HR         720
IT         900
Name: Salary, dtype: int64

In [37]:
df.groupby("Department")["Name"].count()

Department
Finance    1
HR         2
IT         2
Name: Name, dtype: int64

In [38]:
df.groupby("Department")["Salary"].agg(["mean", "min", "max"])

             mean  min  max
Department
Finance     850.0  850  850
HR          685.0  650  720
IT          840.0  780  900

In [41]:
df.groupby([("Department")["Salary"].agg(["mean", "max"])] [("Department")["Name"].count()])

<>:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
<>:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
<>:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
<>:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
/tmp/ipykernel_1391/1238156922.py:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
  df.groupby([("Department")["Salary"].agg(["mean", "max"])] [("Department")["Name"].count()])
/tmp/ipykernel_1391/1238156922.py:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
  df.groupby([("Department")["Salary"].agg(["mean", "max"])] [("Department")["Name"].count()])

TypeError: string indices must be integers, not 'str'

In [42]:
df.groupby("Department")["Salary"].agg(["mean", "max", "count"])

             mean  max  count
Department
Finance     850.0  850      1
HR          685.0  720      2
IT          840.0  900      2

In [43]:
df[df["Department"].isin(["HR","IT"]) & (df["Salary"] >= 700)].sort_values("Salary", ascending=False)[["Name","Department","Salary"]]

    Name Department  Salary
1  Arjun         IT     900
4   Lina         IT     780
2   Sara         HR     720