<a href="https://colab.research.google.com/github/bimald986-cell/90-Days-of-AI/blob/main/Day_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
scores = np.array([72, 85, 91, 68, 88, 95])

NameError: name 'np' is not defined

In [3]:
results = np.where(scores >= 80, "Pass", "Review")

NameError: name 'np' is not defined

In [4]:
import numpy as np

scores = np.array([72, 85, 91, 68, 88, 95])

scores

array([72, 85, 91, 68, 88, 95])

In [5]:
results = np.where(scores >= 80, "Pass", "Review")

results

array(['Review', 'Pass', 'Pass', 'Review', 'Pass', 'Pass'], dtype='<U6')

In [14]:
pass_count = scores >= 80
pass_count.agg("count")

AttributeError: 'numpy.ndarray' object has no attribute 'agg'

In [15]:
pass_count = (scores >= 80).sum()

pass_count

np.int64(4)

In [16]:
below_75 = (scores < 75).sum()
below_75

np.int64(2)

In [21]:
pass_percentage = (scores >= 80).sum()
pass_percentage = pass_percentage / len(scores) * 100
pass_percentage

np.float64(66.66666666666666)

In [25]:
pass_percentage = (scores >= 80).sum()
pass_percentage = pass_percentage / len(scores) * 100
round(pass_percentage, 2)

np.float64(66.67)

In [27]:
pass_percentage = (scores >= 80).sum()
pass_percentage = pass_percentage / len(scores) * 100
pass_percentage = round(pass_percentage, 2)
pass_percentage

np.float64(66.67)

In [32]:
scores = np.array([72, 85, 91, 68, 88, 95])

In [33]:
ratings = np.where(
    scores >= 90,
    "Excellent",
    np.where(
        scores >= 80,
        "Good",
        "Review"
    )
)

ratings

array(['Review', 'Good', 'Excellent', 'Review', 'Good', 'Excellent'],
      dtype='<U9')

In [38]:
decision = np.where(
    scores >= 90,
    "Hire",
    np.where(
        scores >= 75,
        "Interview",
        "Reject"
    )
)

decision

array(['Reject', 'Interview', 'Hire', 'Reject', 'Interview', 'Hire'],
      dtype='<U9')

In [39]:
import pandas as pd

candidates = pd.DataFrame({
    "Name": ["Asha", "Ravi", "Maya", "Omar", "Sara", "Daniel"],
    "Score": scores,
    "Decision": decision
})

candidates

     Name  Score   Decision
0    Asha     72     Reject
1    Ravi     85  Interview
2    Maya     91       Hire
3    Omar     68     Reject
4    Sara     88  Interview
5  Daniel     95       Hire

In [45]:
hired_candidates = candidates[candidates["Decision"] == "Hire"]

hired_candidates

     Name  Score Decision
2    Maya     91     Hire
5  Daniel     95     Hire

In [46]:
shortlisted_candidates = candidates[candidates["Decision"] == "Interview" | candidates["Decision"] == "Interview" & candidates["Score"] >= 85]

shortlisted_candidates

TypeError: Cannot perform 'ror_' with a dtyped [object] array and scalar of type [bool]

In [48]:
shortlisted_candidates = candidates[(candidates["Decision"] == "Hire") | (candidates["Decision"] == "Interview") & (candidates["Score"] >= 85)]

shortlisted_candidates

     Name  Score   Decision
1    Ravi     85  Interview
2    Maya     91       Hire
4    Sara     88  Interview
5  Daniel     95       Hire

In [49]:
shortlisted_candidates = candidates[
    (
        (candidates["Decision"] == "Hire") |
        (candidates["Decision"] == "Interview")
    )
    & (candidates["Score"] >= 85)
]

shortlisted_candidates

     Name  Score   Decision
1    Ravi     85  Interview
2    Maya     91       Hire
4    Sara     88  Interview
5  Daniel     95       Hire

In [50]:
shortlisted_candidates = candidates[
    (candidates["Decision"] != "Reject") &
    (candidates["Score"] >= 85)
]

shortlisted_candidates

     Name  Score   Decision
1    Ravi     85  Interview
2    Maya     91       Hire
4    Sara     88  Interview
5  Daniel     95       Hire

In [52]:
ranked_shortlist = shortlisted_candidates.sort_values(by="Score", ascending=False)
ranked_shortlist

     Name  Score   Decision
5  Daniel     95       Hire
2    Maya     91       Hire
4    Sara     88  Interview
1    Ravi     85  Interview

In [55]:
top_candidate = ranked_shortlist.head()
top_candidate

     Name  Score   Decision
5  Daniel     95       Hire
2    Maya     91       Hire
4    Sara     88  Interview
1    Ravi     85  Interview

In [56]:
lowest_candidate = ranked_shortlist.tail(1)
lowest_candidate

   Name  Score   Decision
1  Ravi     85  Interview

In [59]:
shortlisted_names = ranked_shortlist["Name"]
shortlisted_names

5    Daniel
2      Maya
4      Sara
1      Ravi
Name: Name, dtype: object

In [61]:
ranked_shortlist = shortlisted_names.reset_index(drop=True)
ranked_shortlist

0    Daniel
1      Maya
2      Sara
3      Ravi
Name: Name, dtype: object

In [62]:
ranked_shortlist = shortlisted_candidates.sort_values(
    by="Score",
    ascending=False
)

ranked_shortlist = ranked_shortlist.reset_index(drop=True)

ranked_shortlist

     Name  Score   Decision
0  Daniel     95       Hire
1    Maya     91       Hire
2    Sara     88  Interview
3    Ravi     85  Interview

In [63]:
ranked_shortlist = ranked_shortlist.reset_index(drop=True)

ranked_shortlist

     Name  Score   Decision
0  Daniel     95       Hire
1    Maya     91       Hire
2    Sara     88  Interview
3    Ravi     85  Interview

In [65]:
strong_candidates = candidates.loc[
    candidates["Score"] >= 85,
    ["Name", "Decision"]
]
strong_candidates

     Name   Decision
1    Ravi  Interview
2    Maya       Hire
4    Sara  Interview
5  Daniel       Hire

In [70]:
AdjustedScore = candidates["Score"] + 5

AdjustedScore

0     77
1     90
2     96
3     73
4     93
5    100
Name: Score, dtype: int64

In [71]:
candidates["AdjustedScore"] = candidates["Score"] + 5

candidates

     Name  Score   Decision  AdjustedScore
0    Asha     72     Reject             77
1    Ravi     85  Interview             90
2    Maya     91       Hire             96
3    Omar     68     Reject             73
4    Sara     88  Interview             93
5  Daniel     95       Hire            100

In [73]:
candidates["FinalStatus"] = np.where(
    scores >= 90,
        "Qualified",
        "Not Qualified"
    )
candidates

     Name  Score   Decision  AdjustedScore    FinalStatus
0    Asha     72     Reject             77  Not Qualified
1    Ravi     85  Interview             90  Not Qualified
2    Maya     91       Hire             96      Qualified
3    Omar     68     Reject             73  Not Qualified
4    Sara     88  Interview             93  Not Qualified
5  Daniel     95       Hire            100      Qualified

In [74]:
candidates["FinalStatus"] = np.where(
    AdjustedScore >= 90,
        "Qualified",
        "Not Qualified"
    )
candidates

     Name  Score   Decision  AdjustedScore    FinalStatus
0    Asha     72     Reject             77  Not Qualified
1    Ravi     85  Interview             90      Qualified
2    Maya     91       Hire             96      Qualified
3    Omar     68     Reject             73  Not Qualified
4    Sara     88  Interview             93      Qualified
5  Daniel     95       Hire            100      Qualified

In [84]:
final_report = candidates[candidates["FinalStatus"] == "Qualified"].sort_values(by="AdjustedScore", ascending=False)
final_report.reset_index(drop=False)
final_report

     Name  Score   Decision  AdjustedScore FinalStatus
5  Daniel     95       Hire            100   Qualified
2    Maya     91       Hire             96   Qualified
4    Sara     88  Interview             93   Qualified
1    Ravi     85  Interview             90   Qualified

In [ ]:
final_report = candidates[
    candidates["FinalStatus"] == "Qualified"
].sort_values(
    by="AdjustedScore",
    ascending=False
)

final_report = final_report.reset_index(drop=True)

final_report

In [ ]:
final_report = (
    candidates[candidates["FinalStatus"] == "Qualified"]
    .sort_values(by="AdjustedScore", ascending=False)
    .reset_index(drop=True)
)

final_report